### PR TITLE
Added missing files to the silverlight NuGet packages (Fixed #82)

### LINKED ISSUE #82: Specific version of `CUITe.Silverlight.dll` missing in all of the CUITe.Silverlight NuGet packages
There are specific versions of `CUITe.Silverlight.dll` missing in all of the CUITe.Silverlight NuGet packages.

For example, `CUITe.Silverlight.dll` may be missing for NuGet packages that target .NET 4.0 and others that target .NET 4.5.

### PR DESCRIPTION
**Pull request by ramiabughazaleh**
updated build to make ConfigurationName dynamic, default is Release
checking for errors on each build step and failing on first error
consolidated conflicting values for the VisualStudioVersion property
defining conditional compilation symbols based on the VisualStudioVersion property
fixed CUITe.Integration.Tests
removed references to conditional compilation symbol SILVERLIGHT_SUPPORT
added By.ControlType and By.ControlInstance search configurations
removed references to Microsoft.VisualStudio.TestTools.UITest.Extension.Silverlight in non-silverlight projects
made WebDevServer port dynamic to avoid re-using ports that may already be in use
Installing Microsoft Silverlight 5 Developer Runtime for Windows (64 bit) during build
using SilverlightUIAutomationHelper.dll version from SilverlightVersion project property
automatically limiting searching for silverlight controls by its parent
added silverlight child window and corresponding test

### CODE REVIEW

**Comment by icnocop** [comment]
I'm still trying to resolve/troubleshoot why the silverlight tests fail for these on the build server.
They work on my machine. :grin:

**Comment by FantasticFiasco** [comment]
Tell me if you wan't me to help you in any way, run it on my machine or whatever.

**Comment by icnocop** [comment]
Thank you.

I just resolved the build issue, as the last build succeeded, and so this PR is now ready for your review, whenever you have the time.

Thank you! :smile:

**Comment by FantasticFiasco** [comment]
The code looks really good, and the build on AppVeyor succeeded. Seems to be a good day for CUITe.

**Pull request merged**
