### PR TITLE
Fixed #104 - Added support for getting children of a WinControl

### LINKED ISSUE #104: Add support to find a WinControl by index
I would like to be able to find a WinControl by index.

In some cases, Win32 controls on a dialog that are created do not have a consistent unique identifier.

For example, in an MSI: https://sourceforge.net/p/wix/feature-requests/535/

When trying to replace the use of TestStack.White with CUIte, this is a missing piece, as TestStack.White supports this kind of search criteria:
https://github.com/TestStack/White/blob/master/src/TestStack.White/UIItems/Finders/SearchCriteria.cs#L63

For example,
`WinText labelControl = myDialog.Find<WinText>(By.Index(1));`

### PR DESCRIPTION
**Pull request by ramiabughazaleh**

### CODE REVIEW

**Comment by icnocop** [comment]
Hi @FantasticFiasco .

Do you have some time to provide any feedback?

Thank you! :)

**Review by FantasticFiasco — APPROVED** [review]
This looks splendid to me!

**Comment by FantasticFiasco** [comment]
Sorry it took some time, I was unable to review the code yesterday. Nice going with the improvements!

**Comment by icnocop** [comment]
Thank you for the quick feedback! :)

**Pull request merged**
