### PR TITLE
WinForms controls and Control Name

### PR DESCRIPTION
**Pull request by FantasticFiasco**
## Introduction

I've implemented support for searching for WinForms controls using their control name. That was something lacking from the previous implementation of CUITe and the reason for numerous ignored tests.
## Background

It seems like different teams at Microsoft implemented the support for WinForms and WPF, and they never got together and talked about APIs. One thing that has bugged me from the start was that searching for WinForms controls using their control name differes from searching for WPF controls using their automation id.

I think the WPF team got it right. When searching for a WPF control using its automation id, the search property is attached to the control itself, e.g. a button has a search property stating its automation id.
This is not the case when it comes to WinForms. The control name search property is not attached to the control itself, but its parent. E.g. a button has not a search property stating its control name, but the parent does.

I wanted to remove this obscurity when it comes to CUITe and made sure that the syntax of searching for WinForms controls using the control name is identical to how controls in WPF as searched for using their automation id. This of course makes the implementation in CUITe a bit more problematic, but the benefit of letting our consumers use the straightforward API is totally worth the effort in doing the implementation.
## Syntax

The following example displays how to use the `ControlName` method:

```
public bool ButtonExists
{
    get { return Find<WinButton>(By.ControlName("button")).Exists; }
}
```

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
Will take a look at it.

**Comment by FantasticFiasco** [comment]
@icnocop can you take a quick look at it? It could be something to do with AppVeyor. I think there are to many errors for it to have anything to do with my changes.

**Comment by icnocop** [comment]
I think the problem here is because we're not using `<HintPaths>` for some of the references in `Sut.HtmlTests.csproj`, among other places:

```
      <ItemGroup>
        <Reference Include="Microsoft.VisualStudio.QualityTools.CodedUITestFramework, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Common, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
        <Reference Include="Microsoft.VisualStudio.TestTools.UITesting, Version=10.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
          <Private>False</Private>
        </Reference>
      </ItemGroup>
```

I think we should create something similar to `SilverlightExtension.targets`.

**Comment by FantasticFiasco** [comment]
I've created a targets file for CUIT references, complementing the one for Silverlight references but build still breaks. It is complaining about `CodedUITest`, and that attribute is not part of the assemblies we keep in Thirdparty I think?

_Microsoft.VisualStudio.TestTools.UITest.Extension_ and _Microsoft.VisualStudio.TestTools.UITesting_ have been part of Thirdparty, but _Microsoft.VisualStudio.QualityTools.CodedUITestFramework_ and _Microsoft.VisualStudio.TestTools.UITest.Common_ never has, and previous builds worked.

**Comment by icnocop** [comment]
Thank you.

I just added those dlls.

**Comment by FantasticFiasco** [comment]
Rebased my branch, will add the two files to the targets file tonight.

**Comment by FantasticFiasco** [comment]
@icnocop Please take a look at the error, it has nothing to do with my PR.

**Comment by icnocop** [comment]
Sorry, I had RDP temporarily enabled which caused the build to timeout.
I removed it, and now the build succeeds, but some tests are failing.

**Comment by FantasticFiasco** [comment]
I don't think the failing tests are relating to my PR. Some of them are WPF tests. E.g. I haven't made any significant changes to WPF, still some of those tests fail.

Could you please verify that the tests succeed on your computer, because if they do I guess we might need to some changes for the build server, but at current point I am confused about what changes the build server is requiring.

**Comment by icnocop** [comment]
It succeeded when I temporarily enabled RDP and connected to the build machine before the build started and before the tests ran.

**Comment by icnocop** [comment]
I'll retry the build again without connecting to RDP to see what happens.

**Comment by icnocop** [comment]
It seems the tests only succeed when I'm connected using RDP.
It may have something to do with the screen resolution, but I'm not certain.
I will try to update the build script to keep screen shots from failed tests soon.

Thank you.

**Comment by FantasticFiasco** [comment]
I'll wait with merging the PR, thank you for your help.

**Comment by icnocop** [comment]
I committed some changes to use DeploymentItem instead of hard-coded paths to applications under test which should help us troubleshoot test failures on appveyor.

See https://ci.appveyor.com/project/icnocop/cuite/build/2.0.137/tests for an example test report.

Let me know if there's a better way to merge these changes into your branch rather than you having to do a rebase.

Thank you.

**Comment by icnocop** [comment]
Or we can just merge the PR because we know that it builds and tests pass under "normal" conditions.
See https://ci.appveyor.com/project/icnocop/cuite/build/2.0.135

**Comment by FantasticFiasco** [comment]
Nice with the test report!

I would like to do the merge, arguing that our problems are not related to this PR and also exists on branch _master_.

If you agree, I'll do the merge.

**Comment by icnocop** [comment]
Yes, it is fine to do the merge. Thank you.

**Comment by icnocop** [comment]
I think we're running into the same problem as another user: http://help.appveyor.com/discussions/problems/3586-black-screenshots

**Comment by FantasticFiasco** [comment]
Lets hope you get a reply and we can sort this out.

**Pull request merged**
