### PR TITLE
Moved Telerik ComboBox

### PR DESCRIPTION
**Pull request by FantasticFiasco**
Moved Telerik ComboBox to a sub-namespace of 'CUITe.Controls.HtmlControls' since it is a HTML control.

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
@icnocop Have you done anything regarding Firefox on AppVeyor? It seems that the test `SetText_OnHtmlEditUsingFirefox_Succeeds` hangs, and after 40 min the build is aborted.

**Comment by icnocop** [comment]
No, I have not, but I will take a look tonight.  Thank you.

**Comment by icnocop** [comment]
I enabled RDP and logged in before the build and everything worked fine. I'll try to rebuild without establishing an RDP connection and see what happens.

**Comment by icnocop** [comment]
The build succeeded without establishing an RDP connection. I'm not sure what it could have been. :8ball:

**Comment by FantasticFiasco** [comment]
Thanks for the help, the issue got fixed, whatever it was.

**Pull request merged**
