### PR TITLE
Support for VS2015

### PR DESCRIPTION
**Pull request by FantasticFiasco**
## Description

This PR is related to issue #30 and adds support for Visual Studio 2015. In the process of VS2015 support I also decided to solve the following issues:
- Customers had to install the Silverlight plugin even though they didn't test a Silverlight application.
- The NuGet packages targeted individual Visual Studio versions which meant that the number of packages increased with the number of supported VS versions.
## NuGet packages

I've reworked the NuGet packages. Currently the following packages are built:
- **CUITe.2.0.0-beta**: HTML/Telerik/WinForms/WPF support for VS2010, VS2012, VS2013 and VS2015
- **CUITe.Silverlight.VS2010.2.0.0-beta**: Silverlight support for VS2010
- **CUITe.Silverlight.VS2012.2.0.0-beta**: Silverlight support for VS2012
- **CUITe.Silverlight.VS2013.2.0.0-beta**: Silverlight support for VS2013

The main difference is that we now have one package that support all VS versions when it comes to HTML/Telerik/WinForms/WPF.

With Silverlight we still have the situation where we have one package per supported VS version, and no support for VS2015. The reason as to why we can't have only one Silverlight package for all VS versions is that the Silverlight plugin didn't keep the same public key token for all VS versions. If they would we could use assembly redirects as we do with the HTML/Telerik/WinForms/WPF (from now on CUITe) package. The reason as to why we don't support VS2015 is that a Silverlight plugin for that version at the time of this PR hasn't been released.
## NuGet implementation details

The NuGet specifications are now part of the project they represent. I've added them as embedded resources because if they have a _Build Action_ of _None_ or _Content_ the first NuGet specification in the project automatically will be picked up by the pack operation, and in the _CUITe.Silverlight_ project we have three specifications.

As mentions previously, the CUITe package uses assembly redirects to support all VS versions. It contains scripts that investigates the currently running VS version, i.e. the VS version installing the NuGet package, and updates the _app.config_ with assembly redirects for CUITe. The package contains the following script files:
- **app.config.transform**: Is an empty configuration file and serves the purpose of creating a config file if none exists.
- **app.config.install.xdt**: Contains the configuration file transformation that adds assembly redirects. Would be ignored if the project didn't contain a configuration file, thus its success is based on the fact that _app.config.transform_ can add a configuration file. The assembly redirects contains a placeholder for the currently running VS version.
- **install.ps1**: Contains a script that finds and loads the configuration file and replaces the assembly redirect placeholder with information about the currently running VS version.
- **app.config.uninstall.xdt**: Configuration file transformation that removes the assembly redirect when package is uninstalled.
## Build script changes

The MSBuild project _Build.proj_ has been changed. It now contains the following targets:
- **Build**: Builds CUITe for all supported versions
- **BuildSilverlight**: Builds CUITe Silverlight for all supported versions
- **Pack**: Creates CUITe NuGet package
- **PackSilverlight**: Creates CUITe Silverlight NuGet packages

These changes will most certainly affect the build scripts on Appveyor, and these will have to be updated before I merge the PR.
## Help with testing

I need help with testing. I've verified that everything works on VS2013 and VS2015, but haven't verified VS2010 and VS2012.

Again, thanks for all support you've given me. You are truly a excellent maintainer.

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
I have updated the _README_ to accommodate for the changes but got confused. Aren't we supporting Silverlight for VS2010?

**Comment by icnocop** [comment]
Yes, we're supporting Silverlight for Visual Studio 2010.

**Comment by icnocop** [comment]
I added a comment here: https://github.com/FantasticFiasco/cuite/commit/d1813dd5d76a74098302a5dcdd0450a703db9086
Basically, I think the build is failing because there are a couple of missing `<HintPath>...</HintPath>` in CUITe.csproj.

**Comment by FantasticFiasco** [comment]
I answered you on the same place. I don't think the hint paths are the issue, because the hint paths are there in the PR. I added them in a later commit.

Can it be something else that causes the build to fail? Can you build using _Build.bat_?

**Comment by FantasticFiasco** [comment]
From the latest AppVeyor log the following can be found:

```
To install Microsoft Visual Studio UI Test Plugin for Silverlight, you must have one of the following Visual Studio 2012 SKUs installed on your computer: Ultimate, Premium, Test Professional, Test Agent, Test Controller, Team Foundation Server
```

Doesn't that seem fishy?

**Comment by icnocop** [comment]
That was a test build where I tried to install the Microsoft Visual Studio UI Test Plugin for Silverlight for Visual Studio 2012.  But we shouldn't need to install it because the necessary binaries are in the ThirdParty directory. See if the previous build log [here](https://ci.appveyor.com/project/icnocop/cuite/build/2.0.89).

It contains the errors  
`C:\Program Files (x86)\MSBuild\12.0\bin\Microsoft.Common.CurrentVersion.targets(1697,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.TestTools.UITest.Extension, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\projects\cuite\src\CUITe\CUITe.csproj]`  
and  
`error CS0234: The type or namespace name 'VisualStudio' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]`

So I'm thinking we need to tell msbuild where to look for that dll (Microsoft.VisualStudio.TestTools.UITest.Extension.dll) and so we need to add hint paths like this:

```
<Reference Include="Microsoft.VisualStudio.TestTools.UITest.Extension, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
  <Private>False</Private>
  <HintPath>..\ThirdParty\CUIT\v12\Microsoft.VisualStudio.TestTools.UITest.Extension.dll</HintPath>
</Reference>
<Reference Include="Microsoft.VisualStudio.TestTools.UITesting, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, processorArchitecture=MSIL">
  <Private>False</Private>
  <HintPath>..\ThirdParty\CUIT\v12\Microsoft.VisualStudio.TestTools.UITesting.dll</HintPath>
</Reference>
```

just like the other references.

**Comment by FantasticFiasco** [comment]
Looks like you where right!

**Comment by FantasticFiasco** [comment]
Do you want more time to review at the PR or feel confident with the changes?

**Comment by icnocop** [comment]
Looks good to me. Thank you! :)

**Pull request merged**
