### PR TITLE
By syntax

### PR DESCRIPTION
**Pull request by FantasticFiasco**
## Description

This PR is related to issue #27. I've implemented a class called `By` that serves as the starting point for building up your search properties.
## Example

Instead of writing

```
var somebutton = Find<WpfButton>("Name=SomeName;Id=SomeId");
```

one can now write

```
var somebutton = Find<WpfButton>(By.Name("SomeName").AndId("SomeId"));
```

### CODE REVIEW

**Comment by FantasticFiasco** [comment]
The CI failed after Mozilla Firefox 27.0.1 successfully installed.

**Comment by icnocop** [comment]
Thank you.

I will try to fix the build errors ASAP so the tests can run on the new code before we merge it.

**Comment by icnocop** [comment]
There seem to be a couple more compiler errors:

Caches\PropertyNamesCache.cs(15,43): error CS0246: The type or namespace name 'IReadOnlyCollection' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Caches\PropertyNamesCache.cs(30,16): error CS0246: The type or namespace name 'IReadOnlyCollection' could not be found (are you missing a using directive or an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightButton.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightCalendar.cs(4,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightCell.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightCheckBox.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightComboBox.cs(3,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightControl.cs(5,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightDataPager.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightDatePicker.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightEdit.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightHyperlink.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightImage.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightLabel.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightList.cs(4,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightPassword.cs(3,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightRadioButton.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightSlider.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightSpinner.cs(3,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightTab.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightTabItem.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightTable.cs(3,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightText.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Controls\SilverlightControls\SilverlightTree.cs(2,65): error CS0234: The type or namespace name 'SilverlightControls' does not exist in the namespace 'Microsoft.VisualStudio.TestTools.UITesting' (are you missing an assembly reference?) [C:\projects\cuite\src\CUITe\CUITe.csproj]
Done Building Project "C:\projects\cuite\src\CUITe\CUITe.csproj" (Rebuild target(s)) -- FAILED.
Done Building Project "C:\projects\cuite\src\build.proj" (Build;Pack target(s)) -- FAILED.

**Comment by FantasticFiasco** [comment]
That seems pretty strange, IReadonlyCollection is part of the .NET framework. Can you compile the PR on your computer?

**Comment by icnocop** [comment]
IReadOnlyCollection is available only in .NET 4.5+.

The error also occurs on my machine, specifically when compiling CUITe.csproj and targeting .NET 4.0.

For example, run Build.bat.

Thank you.

**Comment by FantasticFiasco** [comment]
Ah, did't compile for all versions. Will look into that. Sorry

**Comment by FantasticFiasco** [comment]
Here we go, everything is green! Thanks for the support.

**Comment by FantasticFiasco** [comment]
Btw, tomorrow and one week forward I will be unable to contribute. i have vacation and will be going on a trip. If they have wifi on the resort I will be able to repond to questions, otherwise I wont.

**Comment by icnocop** [comment]
That's not a problem at all.

That you again for your contributions and have a great vacation! :)

**Pull request merged**
