### PR TITLE
Issue #83

### PR DESCRIPTION
**Pull request by aannenko**
Three new members are added to the ControlBase class. They allow to work with control's visibility.

### CODE REVIEW

**Comment by aannenko** [comment]
I also added a TryGetClickablePointMethod so that it could be used not only implicitly inside the visibility related methods.

**Comment by FantasticFiasco** [comment]
@icnocop Any comments?

**Comment by icnocop** [comment]
There are a lack of tests. :wink: 
Other than that, thank you for the pull request, @aannenko! :smile:

**Comment by FantasticFiasco** [comment]
You should also update the changelog document and add your name there.

**Comment by aannenko** [comment]
Well, I don't have any idea on how to test a WPF part of this... Sorry...
Can you help me a bit with this? What do I have to write? Tests for HTML and... something else?

**Comment by FantasticFiasco** [comment]
I'll see what I can do with it, sorry for the long sleep.

**Comment by FantasticFiasco** [comment]
@aannenko  I took the liberty to add your name to _CHANGELOG.md_. Because of that I had to create a new PR and close this one. Hope you don't mind...

@icnocop I don't have permissions to publish package on NuGet, can you do that?

@aannenko Hope your project is going well and that you get any benefit from using CUITe. Thank you very much for your interest and contributions to this project!

**Comment by icnocop** [comment]
@FantasticFiasco, NuGet packages are automatically published during the build. :)

**Comment by FantasticFiasco** [comment]
@icnocop Oh, nice!
The PR was successful on AppVeyor, but I didn't manage to get master through even though I tried twice.

**Comment by aannenko** [comment]
@FantasticFiasco Thanks a lot! :)

**Comment by icnocop** [comment]
@FantasticFiasco , I just re-invoked the build on the commit and it succeeded. It failed last time because of an unstable test. The unstable test is Sut.HtmlTest.HtmlControlTests.SetText_OnTelerikASPNETComboBox_SelectsItemByText which actually tests against a website in production which isn't very ideal. So, as usual the test succeeds the second time it is run. :smirk:

**Comment by FantasticFiasco** [comment]
@icnocop Business as usual :smile:

**Pull request closed without merging**
